#!/usr/bin/env python3

# From wikipedia
r1_universities = [
    "Arizona State University",
    "Auburn University",
    "Baylor University",
    "Binghamton University",
    "Boston College",
    "Boston University",
    "Brandeis University",
    "Brown University",
    "California Institute of Technology",
    "Carnegie Mellon University",
    "Case Western Reserve University",
    "Clemson University",
    "Colorado School of Mines",
    "Colorado State University",
    "Columbia University",
    "Cornell University",
    "Dartmouth College",
    "Drexel University",
    "Duke University",
    "Emory University",
    "Florida International University",
    "Florida State University",
    "George Mason University",
    "George Washington University",
    "Georgetown University",
    "Georgia Institute of Technology",
    "Georgia State University",
    "Graduate Center, CUNY",
    "Harvard University",
    "Indiana University Bloomington",
    "Iowa State University",
    "Johns Hopkins University",
    "Kansas State University",
    "Kent State University",
    "Louisiana State University",
    "Massachusetts Institute of Technology",
    "Michigan State University",
    "Mississippi State University",
    "Montana State University",
    "New Jersey Institute of Technology",
    "New York University",
    "North Carolina State University",
    "North Dakota State University",
    "Northeastern University",
    "Northwestern University",
    "Ohio State University",
    "Ohio University",
    "Oklahoma State University–Stillwater",
    "Old Dominion University",
    "Oregon State University",
    "Pennsylvania State University",
    "Princeton University",
    "Purdue University",
    "Rensselaer Polytechnic Institute",
    "Rice University",
    "Rutgers University–New Brunswick",
    "Stanford University",
    "Stony Brook University",
    "Syracuse University",
    "Temple University",
    "Texas A&M University",
    "Texas Tech University",
    "Tufts University",
    "Tulane University",
    "University at Albany, SUNY",
    "University at Buffalo",
    "University of Alabama",
    "University of Alabama at Birmingham",
    "University of Alabama in Huntsville",
    "University of Arizona",
    "University of Arkansas",
    "University of California, Berkeley",
    "University of California, Davis",
    "University of California, Irvine",
    "University of California, Los Angeles",
    "University of California, Riverside",
    "University of California, San Diego",
    "University of California, Santa Barbara",
    "University of California, Santa Cruz",
    "University of Central Florida",
    "University of Chicago",
    "University of Cincinnati",
    "University of Colorado Boulder",
    "University of Colorado Denver",
    "University of Connecticut",
    "University of Delaware",
    "University of Denver",
    "University of Florida",
    "University of Georgia",
    "University of Hawaii at Manoa",
    "University of Houston",
    "University of Illinois Chicago",
    "University of Illinois Urbana-Champaign",
    "University of Iowa",
    "University of Kansas",
    "University of Kentucky",
    "University of Louisiana at Lafayette",
    "University of Louisville",
    "University of Maine",
    "University of Maryland, Baltimore County",
    "University of Maryland, College Park",
    "University of Massachusetts Amherst",
    "University of Memphis",
    "University of Miami",
    "University of Michigan",
    "University of Minnesota",
    "University of Mississippi",
    "University of Missouri",
    "University of Montana",
    "University of Nebraska–Lincoln",
    "University of Nevada, Las Vegas",
    "University of Nevada, Reno",
    "University of New Hampshire",
    "University of New Mexico",
    "University of North Carolina at Chapel Hill",
    "University of North Texas",
    "University of Notre Dame",
    "University of Oklahoma",
    "University of Oregon",
    "University of Pennsylvania",
    "University of Pittsburgh",
    "University of Rochester",
    "University of South Carolina",
    "University of South Florida",
    "University of Southern California",
    "University of Southern Mississippi",
    "University of Tennessee",
    "University of Texas at Arlington",
    "University of Texas at Austin",
    "University of Texas at Dallas",
    "University of Texas at El Paso",
    "University of Texas at San Antonio",
    "University of Utah",
    "University of Virginia",
    "University of Washington",
    "University of Wisconsin–Madison",
    "University of Wisconsin–Milwaukee",
    "Utah State University",
    "Vanderbilt University",
    "Virginia Commonwealth University",
    "Virginia Tech",
    "Washington State University",
    "Washington University in St. Louis",
    "Wayne State University",
    "West Virginia University",
    "Yale University",
]
